### ISSUE TITLE
Polish Readme

### ISSUE THREAD

**Issue by Pterosaur** [OpenNetLab/AlphaRTC#12]
Please update and polish the [Readme](https://github.com/OpenNetLab/AlphaRTC/blob/dev/README.md) and [Peerconnection Tutorial](https://github.com/OpenNetLab/AlphaRTC/blob/dev/examples/peerconnection/serverless/serverless-peerconnection-tutorial.md#serverless-peerconnection-application-tutorial)

**Comment by XIAZY** [comment]
#14
