### ISSUE TITLE
poor performance of ONNX model 

### ISSUE THREAD

**Issue by Alexyali** [OpenNetLab/AlphaRTC#81]
hello,
I am interested in AlphaRTC and did some network test, but the strange experiment results confused me very much.

Firstly, I compile AlphaRTC in win10 from scratch, and generated `peerconnection_serverless.exe`. Then I test ONNX Estimator and PyInfer Estimator separately in the local loopback network, which has no bandwidth limitation. I set the returned bandwidth to be 1Mbps in `BandwidthEstimator.py` for PyInfer. 

The test results are shown below:

| model            | delay_95%/ms | avg_recv_rate/kbps |
| --------------  | ------------ | ------------------ |
| onnx              | 1                | 68                 |
| pyinfer (1M)  | 1                | 590                |

There are two questions that i am confused:
- why onnx model can only generate 68kbps data rate?
- why pyinfer(1M) cannot get nearly 1Mbps data rate? i guess that the origin data rate of video source is nearly 590kbps.

Thanks very much!

**Comment by Alexyali** [comment]
this is the recv_rate result of onnx model under unlimited bandwidth condition
![ssrc_2291422075_rate](https://user-images.githubusercontent.com/48520322/129320269-f643d5de-0eb7-4ef7-a8f9-3ee2b4403ade.png)

**Comment by jeongyooneo** [comment]
Hi @Alexyali, sorry for the late response.
The ONNX and PyInfer bandwidth estimator needs to be a converged RL-based bandwidth estimator. Default provided estimators are simple skeleton models, so the low performance.
You can try an open-sourced AlphaRTC-testable checkpoint in the artifact of HRCC, published in MMSys 2021 (https://github.com/thegreatwb/HRCC).
