### ISSUE TITLE
Inconsistent original/output video size

### ISSUE THREAD

**Issue by ChengChen2020** [OpenNetLab/AlphaRTC#82]
Hi,

I used the default setting for `peerconnection_serverless`. However, the original ~1s test.yuv video would become ~19s output video after transmission.

Could someone help me out here?

Thanks!

**Comment by Azson** [comment]
Hi @ChengChen2020 , it is right. You can set the duration time in sender's configuration json file. The key is "autoclose". And AlphaRTC will repeat the video if the video's duration time is less than the key "autoclose".
