### ISSUE TITLE
Dose alphaRTC support the Scalability video coding(SVC)?

### ISSUE THREAD

**Issue by xiaosayin** [OpenNetLab/AlphaRTC#84]
I want to use the SVC in alphaRTC.
Can anybody show how to start the SVC in alphaRTC?

**Comment by jeongyooneo** [comment]
Hi @xiaosayin, thanks for the suggestion!
Unfortunately, current version of AlphaRTC does not yet support SVC. We're open to code contributions on the issue, so feel free to open a PR on this!
