### ISSUE TITLE
Core dumped at running the receiver

### ISSUE THREAD

**Issue by pkarimib** [OpenNetLab/AlphaRTC#88]
I could successfully run the code until it stoped working altogether with this error:

```
# Fatal error in: ../../examples/peerconnection/serverless/peer_connection_client.cc, line 65
# last system error: 98
# Check failed: false
# receiver.sh: line 6: 1890305 Aborted

```

I did not recompile or change the pipeline at all, I just reran the code. Do you know what could be the issue? Thanks a lot!

**Comment by jeongyooneo** [comment]
Hi @pkarimib, sorry for the late response. 
The error seems to be the port binding error. Please check receiver- and sender-side JSON config files (e.g. `receiver-pyinfer.json` and `sender-pyinfer.json`).

<img width="615" alt="image" src="https://github.com/OpenNetLab/AlphaRTC/assets/6097406/16937414-8bfd-4b40-911d-155f6ef665f2">

**Comment by jeongyooneo** [comment]
Closing this issue as there is no further discussion. 
@pkarimib Please feel free to open any issue if there's any!
